### PR TITLE
Updates the script to conform with the new '--flags FLAG1,FLAG2' flags

### PR DESCRIPTION
**Pull request by muldjord**
I've updated the skyscraper.sh script to use the `--flags FLAG1,FLAG2` format. I've also added version checks for at least 3.5 to the gathering and generating functions that will display a message in case the user needs to update. Lastly I've updated all the places where the old flags were mentioned in the help texts so they now show the new `--flags` versions.

### CODE REVIEW

**Comment by joolswills** [comment]
Thanks. I updated the skyscraper binaries on the 24th April. Do I need to update them or?

**Comment by muldjord** [comment]
Yes, that would be great, thanks. A binary of 3.5.x is needed for get past the version check. Latest version is 3.5.2.

**Comment by joolswills** [comment]
Latest version is failing kn

**Comment by joolswills** [comment]
Latest version is failing on Stretch. I'll provide a log - probably due to older dependencies or so.

**Comment by joolswills** [comment]
```
Info: creating stash file /home/pi/RetroPie-Setup/tmp/build/skyscraper/.qmake.stash
g++ -c -pipe -std=c++11 -O2 -Wall -W -D_REENTRANT -fPIC -DVERSION=\"3.5.2\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_CORE_LIB -I. -I. -isystem /usr/include/arm-linux-gnueabihf/qt5 -isystem /usr/include/arm-linux-gnueabihf/qt5/QtGui -isystem /usr/include/arm-linux-gnueabihf/qt5/QtNetwork -isystem /usr/include/arm-linux-gnueabihf/qt5/QtXml -isystem /usr/include/arm-linux-gnueabihf/qt5/QtCore -I. -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -o main.o src/main.cpp
g++ -c -pipe -std=c++11 -O2 -Wall -W -D_REENTRANT -fPIC -DVERSION=\"3.5.2\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_CORE_LIB -I. -I. -isystem /usr/include/arm-linux-gnueabihf/qt5 -isystem /usr/include/arm-linux-gnueabihf/qt5/QtGui -isystem /usr/include/arm-linux-gnueabihf/qt5/QtNetwork -isystem /usr/include/arm-linux-gnueabihf/qt5/QtXml -isystem /usr/include/arm-linux-gnueabihf/qt5/QtCore -I. -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -o skyscraper.o src/skyscraper.cpp
g++ -c -pipe -std=c++11 -O2 -Wall -W -D_REENTRANT -fPIC -DVERSION=\"3.5.2\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_CORE_LIB -I. -I. -isystem /usr/include/arm-linux-gnueabihf/qt5 -isystem /usr/include/arm-linux-gnueabihf/qt5/QtGui -isystem /usr/include/arm-linux-gnueabihf/qt5/QtNetwork -isystem /usr/include/arm-linux-gnueabihf/qt5/QtXml -isystem /usr/include/arm-linux-gnueabihf/qt5/QtCore -I. -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -o netcomm.o src/netcomm.cpp
g++ -c -pipe -std=c++11 -O2 -Wall -W -D_REENTRANT -fPIC -DVERSION=\"3.5.2\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_CORE_LIB -I. -I. -isystem /usr/include/arm-linux-gnueabihf/qt5 -isystem /usr/include/arm-linux-gnueabihf/qt5/QtGui -isystem /usr/include/arm-linux-gnueabihf/qt5/QtNetwork -isystem /usr/include/arm-linux-gnueabihf/qt5/QtXml -isystem /usr/include/arm-linux-gnueabihf/qt5/QtCore -I. -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -o xmlreader.o src/xmlreader.cpp
src/main.cpp: In function ‘int main(int, char**)’:
src/main.cpp:229:17: error: ‘class QCommandLineOption’ has no member named ‘setFlags’
   skippedOption.setFlags(QCommandLineOption::HiddenFromHelp);
                 ^~~~~~~~
src/main.cpp:229:26: error: ‘HiddenFromHelp’ is not a member of ‘QCommandLineOption’
   skippedOption.setFlags(QCommandLineOption::HiddenFromHelp);
                          ^~~~~~~~~~~~~~~~~~
src/main.cpp:231:18: error: ‘class QCommandLineOption’ has no member named ‘setFlags’
   nocoversOption.setFlags(QCommandLineOption::HiddenFromHelp);
                  ^~~~~~~~
src/main.cpp:231:27: error: ‘HiddenFromHelp’ is not a member of ‘QCommandLineOption’
   nocoversOption.setFlags(QCommandLineOption::HiddenFromHelp);
                           ^~~~~~~~~~~~~~~~~~
src/main.cpp:233:23: error: ‘class QCommandLineOption’ has no member named ‘setFlags’
   noscreenshotsOption.setFlags(QCommandLineOption::HiddenFromHelp);
                       ^~~~~~~~
src/main.cpp:233:32: error: ‘HiddenFromHelp’ is not a member of ‘QCommandLineOption’
   noscreenshotsOption.setFlags(QCommandLineOption::HiddenFromHelp);
                                ^~~~~~~~~~~~~~~~~~
src/main.cpp:235:18: error: ‘class QCommandLineOption’ has no member named ‘setFlags’
   nowheelsOption.setFlags(QCommandLineOption::HiddenFromHelp);
                  ^~~~~~~~
src/main.cpp:235:27: error: ‘HiddenFromHelp’ is not a member of ‘QCommandLineOption’
   nowheelsOption.setFlags(QCommandLineOption::HiddenFromHelp);
                           ^~~~~~~~~~~~~~~~~~
src/main.cpp:237:20: error: ‘class QCommandLineOption’ has no member named ‘setFlags’
   nomarqueesOption.setFlags(QCommandLineOption::HiddenFromHelp);
                    ^~~~~~~~
src/main.cpp:237:29: error: ‘HiddenFromHelp’ is not a member of ‘QCommandLineOption’
   nomarqueesOption.setFlags(QCommandLineOption::HiddenFromHelp);
                             ^~~~~~~~~~~~~~~~~~
src/main.cpp:239:28: error: ‘class QCommandLineOption’ has no member named ‘setFlags’
   skipexistingcoversOption.setFlags(QCommandLineOption::HiddenFromHelp);
                            ^~~~~~~~
src/main.cpp:239:37: error: ‘HiddenFromHelp’ is not a member of ‘QCommandLineOption’
   skipexistingcoversOption.setFlags(QCommandLineOption::HiddenFromHelp);
                                     ^~~~~~~~~~~~~~~~~~
src/main.cpp:241:33: error: ‘class QCommandLineOption’ has no member named ‘setFlags’
   skipexistingscreenshotsOption.setFlags(QCommandLineOption::HiddenFromHelp);
                                 ^~~~~~~~
src/main.cpp:241:42: error: ‘HiddenFromHelp’ is not a member of ‘QCommandLineOption’
   skipexistingscreenshotsOption.setFlags(QCommandLineOption::HiddenFromHelp);
                                          ^~~~~~~~~~~~~~~~~~
src/main.cpp:243:28: error: ‘class QCommandLineOption’ has no member named ‘setFlags’
   skipexistingwheelsOption.setFlags(QCommandLineOption::HiddenFromHelp);
                            ^~~~~~~~
src/main.cpp:243:37: error: ‘HiddenFromHelp’ is not a member of ‘QCommandLineOption’
   skipexistingwheelsOption.setFlags(QCommandLineOption::HiddenFromHelp);
                                     ^~~~~~~~~~~~~~~~~~
src/main.cpp:245:30: error: ‘class QCommandLineOption’ has no member named ‘setFlags’
   skipexistingmarqueesOption.setFlags(QCommandLineOption::HiddenFromHelp);
                              ^~~~~~~~
src/main.cpp:245:39: error: ‘HiddenFromHelp’ is not a member of ‘QCommandLineOption’
   skipexistingmarqueesOption.setFlags(QCommandLineOption::HiddenFromHelp);
                                       ^~~~~~~~~~~~~~~~~~
src/main.cpp:247:28: error: ‘class QCommandLineOption’ has no member named ‘setFlags’
   skipexistingvideosOption.setFlags(QCommandLineOption::HiddenFromHelp);
                            ^~~~~~~~
src/main.cpp:247:37: error: ‘HiddenFromHelp’ is not a member of ‘QCommandLineOption’
   skipexistingvideosOption.setFlags(QCommandLineOption::HiddenFromHelp);
                                     ^~~~~~~~~~~~~~~~~~
src/main.cpp:249:17: error: ‘class QCommandLineOption’ has no member named ‘setFlags’
   symlinkOption.setFlags(QCommandLineOption::HiddenFromHelp);
                 ^~~~~~~~
src/main.cpp:249:26: error: ‘HiddenFromHelp’ is not a member of ‘QCommandLineOption’
   symlinkOption.setFlags(QCommandLineOption::HiddenFromHelp);
                          ^~~~~~~~~~~~~~~~~~
src/main.cpp:251:20: error: ‘class QCommandLineOption’ has no member named ‘setFlags’
   nobracketsOption.setFlags(QCommandLineOption::HiddenFromHelp);
                    ^~~~~~~~
src/main.cpp:251:29: error: ‘HiddenFromHelp’ is not a member of ‘QCommandLineOption’
   nobracketsOption.setFlags(QCommandLineOption::HiddenFromHelp);
                             ^~~~~~~~~~~~~~~~~~
src/main.cpp:253:18: error: ‘class QCommandLineOption’ has no member named ‘setFlags’
   relativeOption.setFlags(QCommandLineOption::HiddenFromHelp);
                  ^~~~~~~~
src/main.cpp:253:27: error: ‘HiddenFromHelp’ is not a member of ‘QCommandLineOption’
   relativeOption.setFlags(QCommandLineOption::HiddenFromHelp);
                           ^~~~~~~~~~~~~~~~~~
src/main.cpp:255:18: error: ‘class QCommandLineOption’ has no member named ‘setFlags’
   noresizeOption.setFlags(QCommandLineOption::HiddenFromHelp);
                  ^~~~~~~~
src/main.cpp:255:27: error: ‘HiddenFromHelp’ is not a member of ‘QCommandLineOption’
   noresizeOption.setFlags(QCommandLineOption::HiddenFromHelp);
                           ^~~~~~~~~~~~~~~~~~
src/main.cpp:257:19: error: ‘class QCommandLineOption’ has no member named ‘setFlags’
   nosubdirsOption.setFlags(QCommandLineOption::HiddenFromHelp);
                   ^~~~~~~~
src/main.cpp:257:28: error: ‘HiddenFromHelp’ is not a member of ‘QCommandLineOption’
   nosubdirsOption.setFlags(QCommandLineOption::HiddenFromHelp);
                            ^~~~~~~~~~~~~~~~~~
src/main.cpp:259:18: error: ‘class QCommandLineOption’ has no member named ‘setFlags’
   unattendOption.setFlags(QCommandLineOption::HiddenFromHelp);
                  ^~~~~~~~
src/main.cpp:259:27: error: ‘HiddenFromHelp’ is not a member of ‘QCommandLineOption’
   unattendOption.setFlags(QCommandLineOption::HiddenFromHelp);
                           ^~~~~~~~~~~~~~~~~~
src/main.cpp:261:22: error: ‘class QCommandLineOption’ has no member named ‘setFlags’
   unattendskipOption.setFlags(QCommandLineOption::HiddenFromHelp);
                      ^~~~~~~~
src/main.cpp:261:31: error: ‘HiddenFromHelp’ is not a member of ‘QCommandLineOption’
   unattendskipOption.setFlags(QCommandLineOption::HiddenFromHelp);
                               ^~~~~~~~~~~~~~~~~~
src/main.cpp:263:16: error: ‘class QCommandLineOption’ has no member named ‘setFlags’
   unpackOption.setFlags(QCommandLineOption::HiddenFromHelp);
                ^~~~~~~~
src/main.cpp:263:25: error: ‘HiddenFromHelp’ is not a member of ‘QCommandLineOption’
   unpackOption.setFlags(QCommandLineOption::HiddenFromHelp);
                         ^~~~~~~~~~~~~~~~~~
src/main.cpp:265:23: error: ‘class QCommandLineOption’ has no member named ‘setFlags’
   forcefilenameOption.setFlags(QCommandLineOption::HiddenFromHelp);
                       ^~~~~~~~
src/main.cpp:265:32: error: ‘HiddenFromHelp’ is not a member of ‘QCommandLineOption’
   forcefilenameOption.setFlags(QCommandLineOption::HiddenFromHelp);
                                ^~~~~~~~~~~~~~~~~~
src/main.cpp:267:21: error: ‘class QCommandLineOption’ has no member named ‘setFlags’
   onlymissingOption.setFlags(QCommandLineOption::HiddenFromHelp);
                     ^~~~~~~~
src/main.cpp:267:30: error: ‘HiddenFromHelp’ is not a member of ‘QCommandLineOption’
   onlymissingOption.setFlags(QCommandLineOption::HiddenFromHelp);
                              ^~~~~~~~~~~~~~~~~~
src/main.cpp:269:17: error: ‘class QCommandLineOption’ has no member named ‘setFlags’
   nohintsOption.setFlags(QCommandLineOption::HiddenFromHelp);
                 ^~~~~~~~
src/main.cpp:269:26: error: ‘HiddenFromHelp’ is not a member of ‘QCommandLineOption’
   nohintsOption.setFlags(QCommandLineOption::HiddenFromHelp);
                          ^~~~~~~~~~~~~~~~~~
src/main.cpp:271:16: error: ‘class QCommandLineOption’ has no member named ‘setFlags’
   videosOption.setFlags(QCommandLineOption::HiddenFromHelp);
                ^~~~~~~~
src/main.cpp:271:25: error: ‘HiddenFromHelp’ is not a member of ‘QCommandLineOption’
   videosOption.setFlags(QCommandLineOption::HiddenFromHelp);
                         ^~~~~~~~~~~~~~~~~~
src/main.cpp:273:17: error: ‘class QCommandLineOption’ has no member named ‘setFlags’
   pretendOption.setFlags(QCommandLineOption::HiddenFromHelp);
                 ^~~~~~~~
src/main.cpp:273:26: error: ‘HiddenFromHelp’ is not a member of ‘QCommandLineOption’
   pretendOption.setFlags(QCommandLineOption::HiddenFromHelp);
                          ^~~~~~~~~~~~~~~~~~
src/main.cpp:275:21: error: ‘class QCommandLineOption’ has no member named ‘setFlags’
   interactiveOption.setFlags(QCommandLineOption::HiddenFromHelp);
                     ^~~~~~~~
src/main.cpp:275:30: error: ‘HiddenFromHelp’ is not a member of ‘QCommandLineOption’
   interactiveOption.setFlags(QCommandLineOption::HiddenFromHelp);
                              ^~~~~~~~~~~~~~~~~~
g++ -c -pipe -std=c++11 -O2 -Wall -W -D_REENTRANT -fPIC -DVERSION=\"3.5.2\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_CORE_LIB -I. -I. -isystem /usr/include/arm-linux-gnueabihf/qt5 -isystem /usr/include/arm-linux-gnueabihf/qt5/QtGui -isystem /usr/include/arm-linux-gnueabihf/qt5/QtNetwork -isystem /usr/include/arm-linux-gnueabihf/qt5/QtXml -isystem /usr/include/arm-linux-gnueabihf/qt5/QtCore -I. -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -o compositor.o src/compositor.cpp
```

If this is due to older libraries or so and there's no easy workaround, we may have to disable this module for Stretch. But I'll leave that decision to you. Thanks.

**Comment by joolswills** [comment]
I've updated the binaries for Buster.

**Comment by cmitu** [comment]
Given that the vast majority of users are still on Stretch, I'd prefer not to disable it.
I think there might be a way to make it work with Qt 5.7 from Stretch.

**Comment by cmitu** [comment]
Something like https://gist.github.com/cmitu/c8a3f7062e5689b1a98be60d326ab072 makes it compile on Stretch (with Qt 5.7).

**Comment by joolswills** [comment]
That was quick! :-)

**Comment by muldjord** [comment]
Ah, sorry guys, I'll fix it in my repos promptly so it compiles with 5.7 as well, I hadn't tested that. Stay tuned.

**Comment by joolswills** [comment]
No worries! Thanks - no rush

**Comment by muldjord** [comment]
I've now re-released 3.5.2 with code similar to @cmitu 's suggestion. I've added an additional check for Qt 5.6 (for setHidden) just for good measure.

It should now compile both for Buster and Stretch.

**Comment by joolswills** [comment]
Sorry - but looks like it needs a tweak still

```
Info: creating stash file /home/pi/RetroPie-Setup/tmp/build/skyscraper/.qmake.stash
g++ -c -pipe -std=c++11 -O2 -Wall -W -D_REENTRANT -fPIC -DVERSION=\"3.5.2\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_CORE_LIB -I. -I. -isystem /usr/include/arm-linux-gnueabihf/qt5 -isystem /usr/include/arm-linux-gnueabihf/qt5/QtGui -isystem /usr/include/arm-linux-gnueabihf/qt5/QtNetwork -isystem /usr/include/arm-linux-gnueabihf/qt5/QtXml -isystem /usr/include/arm-linux-gnueabihf/qt5/QtCore -I. -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -o main.o src/main.cpp
g++ -c -pipe -std=c++11 -O2 -Wall -W -D_REENTRANT -fPIC -DVERSION=\"3.5.2\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_CORE_LIB -I. -I. -isystem /usr/include/arm-linux-gnueabihf/qt5 -isystem /usr/include/arm-linux-gnueabihf/qt5/QtGui -isystem /usr/include/arm-linux-gnueabihf/qt5/QtNetwork -isystem /usr/include/arm-linux-gnueabihf/qt5/QtXml -isystem /usr/include/arm-linux-gnueabihf/qt5/QtCore -I. -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -o skyscraper.o src/skyscraper.cpp
g++ -c -pipe -std=c++11 -O2 -Wall -W -D_REENTRANT -fPIC -DVERSION=\"3.5.2\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_CORE_LIB -I. -I. -isystem /usr/include/arm-linux-gnueabihf/qt5 -isystem /usr/include/arm-linux-gnueabihf/qt5/QtGui -isystem /usr/include/arm-linux-gnueabihf/qt5/QtNetwork -isystem /usr/include/arm-linux-gnueabihf/qt5/QtXml -isystem /usr/include/arm-linux-gnueabihf/qt5/QtCore -I. -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -o netcomm.o src/netcomm.cpp
g++ -c -pipe -std=c++11 -O2 -Wall -W -D_REENTRANT -fPIC -DVERSION=\"3.5.2\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_CORE_LIB -I. -I. -isystem /usr/include/arm-linux-gnueabihf/qt5 -isystem /usr/include/arm-linux-gnueabihf/qt5/QtGui -isystem /usr/include/arm-linux-gnueabihf/qt5/QtNetwork -isystem /usr/include/arm-linux-gnueabihf/qt5/QtXml -isystem /usr/include/arm-linux-gnueabihf/qt5/QtCore -I. -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -o xmlreader.o src/xmlreader.cpp
src/main.cpp: In function ‘int main(int, char**)’:
src/main.cpp:279:10: error: ‘class QCommandLineParser’ has no member named ‘setHidden’
   parser.setHidden(skippedOption);
          ^~~~~~~~~
src/main.cpp:280:10: error: ‘class QCommandLineParser’ has no member named ‘setHidden’
   parser.setHidden(nocoversOption);
          ^~~~~~~~~
src/main.cpp:281:10: error: ‘class QCommandLineParser’ has no member named ‘setHidden’
   parser.setHidden(noscreenshotsOption);
          ^~~~~~~~~
src/main.cpp:282:10: error: ‘class QCommandLineParser’ has no member named ‘setHidden’
   parser.setHidden(nowheelsOption);
          ^~~~~~~~~
src/main.cpp:283:10: error: ‘class QCommandLineParser’ has no member named ‘setHidden’
   parser.setHidden(nomarqueesOption);
          ^~~~~~~~~
src/main.cpp:284:10: error: ‘class QCommandLineParser’ has no member named ‘setHidden’
   parser.setHidden(skipexistingcoversOption);
          ^~~~~~~~~
src/main.cpp:285:10: error: ‘class QCommandLineParser’ has no member named ‘setHidden’
   parser.setHidden(skipexistingscreenshotsOption);
          ^~~~~~~~~
src/main.cpp:286:10: error: ‘class QCommandLineParser’ has no member named ‘setHidden’
   parser.setHidden(skipexistingwheelsOption);
          ^~~~~~~~~
src/main.cpp:287:10: error: ‘class QCommandLineParser’ has no member named ‘setHidden’
   parser.setHidden(skipexistingmarqueesOption);
          ^~~~~~~~~
src/main.cpp:288:10: error: ‘class QCommandLineParser’ has no member named ‘setHidden’
   parser.setHidden(skipexistingvideosOption);
          ^~~~~~~~~
src/main.cpp:289:10: error: ‘class QCommandLineParser’ has no member named ‘setHidden’
   parser.setHidden(symlinkOption);
          ^~~~~~~~~
src/main.cpp:290:10: error: ‘class QCommandLineParser’ has no member named ‘setHidden’
   parser.setHidden(nobracketsOption);
          ^~~~~~~~~
src/main.cpp:291:10: error: ‘class QCommandLineParser’ has no member named ‘setHidden’
   parser.setHidden(relativeOption);
          ^~~~~~~~~
src/main.cpp:292:10: error: ‘class QCommandLineParser’ has no member named ‘setHidden’
   parser.setHidden(noresizeOption);
          ^~~~~~~~~
src/main.cpp:293:10: error: ‘class QCommandLineParser’ has no member named ‘setHidden’
   parser.setHidden(nosubdirsOption);
          ^~~~~~~~~
src/main.cpp:294:10: error: ‘class QCommandLineParser’ has no member named ‘setHidden’
   parser.setHidden(unattendOption);
          ^~~~~~~~~
src/main.cpp:295:10: error: ‘class QCommandLineParser’ has no member named ‘setHidden’
   parser.setHidden(unattendskipOption);
          ^~~~~~~~~
src/main.cpp:296:10: error: ‘class QCommandLineParser’ has no member named ‘setHidden’
   parser.setHidden(unpackOption);
          ^~~~~~~~~
src/main.cpp:297:10: error: ‘class QCommandLineParser’ has no member named ‘setHidden’
   parser.setHidden(forcefilenameOption);
          ^~~~~~~~~
src/main.cpp:298:10: error: ‘class QCommandLineParser’ has no member named ‘setHidden’
   parser.setHidden(onlymissingOption);
          ^~~~~~~~~
src/main.cpp:299:10: error: ‘class QCommandLineParser’ has no member named ‘setHidden’
   parser.setHidden(nohintsOption);
          ^~~~~~~~~
src/main.cpp:300:10: error: ‘class QCommandLineParser’ has no member named ‘setHidden’
   parser.setHidden(videosOption);
          ^~~~~~~~~
src/main.cpp:301:10: error: ‘class QCommandLineParser’ has no member named ‘setHidden’
   parser.setHidden(pretendOption);
          ^~~~~~~~~
src/main.cpp:302:10: error: ‘class QCommandLineParser’ has no member named ‘setHidden’
   parser.setHidden(interactiveOption);
          ^~~~~~~~~
g++ -c -pipe -std=c++11 -O2 -Wall -W -D_REENTRANT -fPIC -DVERSION=\"3.5.2\" -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_CORE_LIB -I. -I. -isystem /usr/include/arm-linux-gnueabihf/qt5 -isystem /usr/include/arm-linux-gnueabihf/qt5/QtGui -isystem /usr/include/arm-linux-gnueabihf/qt5/QtNetwork -isystem /usr/include/arm-linux-gnueabihf/qt5/QtXml -isystem /usr/include/arm-linux-gnueabihf/qt5/QtCore -I. -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -o compositor.o src/compositor.cpp
```

**Comment by joolswills** [comment]
Stretch running qt5 5.7.1+dfsg-3+rpi1+deb9u2

I guess setHidden needs newer than 5.7 then ?

**Comment by muldjord** [comment]
I've just re-uploaded 3.5.2 again. This time I've left out setHidden entirely. It seems they removed that option somewhere between 5.6 and 5.8. It's very unlike Qt to do so though, so that has be scratching my head a bit.

Either way, it works just fine without it, it was an aesthetic choice to begin with. Please retry it with the updated release. If it's still not working, could you verify that `main.cpp` no longer has `setHidden` at all? If it does, it is github that isn't updating its release files properly.

**Comment by cmitu** [comment]
@muldjord compilation is ok now on Stretch, thank you.

**Comment by joolswills** [comment]
Thanks. All good and Stretch binaries updated.

**Comment by muldjord** [comment]
Great, thanks guys.
