### PR TITLE
retroarch: fix build with FFmpeg 7+ (libavcodec >= 61.3.100)

### LINKED ISSUE #4189: retroarch: build fails with FFmpeg 7+ (Ubuntu 26.04) — avcodec_close() and AV_INPUT_BUFFER_MIN_SIZE removed
## Environment

- **OS**: Ubuntu 26.04 LTS (Noble Numbat successor, released 2026-04-23)
- **FFmpeg / libavcodec version**: 62.11.100 (ships with FFmpeg 7.x)
- **RetroPie-Setup branch**: master (commit `8ef23f0`)
- **RetroArch tag**: `retropie-v1.19.0`

## Description

Building RetroArch fails when FFmpeg 7.0+ is installed. FFmpeg 7.0 (libavcodec 61.3.100) removed two previously deprecated symbols:

1. **`AV_INPUT_BUFFER_MIN_SIZE`** — removed from `<libavcodec/avcodec.h>`. Was previously `16384`.
2. **`avcodec_close()`** — removed in favour of `avcodec_free_context()`.

## Build errors

```
record/drivers/record_ffmpeg.c: In function 'ffmpeg_init_audio':
record/drivers/record_ffmpeg.c:375:25: error: 'AV_INPUT_BUFFER_MIN_SIZE' undeclared
  375 |    audio->outbuf_size = AV_INPUT_BUFFER_MIN_SIZE;

record/drivers/record_ffmpeg.c: In function 'ffmpeg_free':
record/drivers/record_ffmpeg.c:952:7: error: implicit declaration of function 'avcodec_close'
  952 |       avcodec_close(handle->audio.codec);

cores/libretro-ffmpeg/ffmpeg_core.c: In function 'libretro_ffmpeg_retro_unload_game':
cores/libretro-ffmpeg/ffmpeg_core.c:2092:10: error: implicit declaration of function 'avcodec_close'
 2092 |          avcodec_close(sctx[i]);
```

## Affected files

- `record/drivers/record_ffmpeg.c` (lines 375, 952, 960)
- `cores/libretro-ffmpeg/ffmpeg_core.c` (lines 2092, 2094, 2101)

## Fix

- Replace `avcodec_close()` + `av_free()` with `avcodec_free_context()` (guarded by `LIBAVCODEC_VERSION_INT >= AV_VERSION_INT(61, 3, 100)`)
- Add a `#ifndef AV_INPUT_BUFFER_MIN_SIZE` fallback defining it as `16384`

A patch and the corresponding change to `retroarch.sh` are provided in the linked PR.

## References

- FFmpeg 7.0 changelog: https://ffmpeg.org/index.html#news
- `avcodec_close()` removal: https://github.com/FFmpeg/FFmpeg/commit/ (removed in libavcodec 61.3.100)
- Ubuntu 26.04 release: https://ubuntu.com/blog/ubuntu-26-04-lts

### PR DESCRIPTION
**Pull request by manzolo**
## Summary

Fixes #4189

RetroArch fails to build on systems with FFmpeg 7.0+ (e.g. Ubuntu 26.04, released 2026-04-23, which ships libavcodec 62.11.100). Two previously deprecated symbols were fully removed in FFmpeg 7.0 (libavcodec 61.3.100):

- `AV_INPUT_BUFFER_MIN_SIZE` — removed from `<libavcodec/avcodec.h>`
- `avcodec_close()` — replaced by `avcodec_free_context()`

## Changes

- **`scriptmodules/emulators/retroarch/01-ffmpeg7-api-compat.diff`** — patch applied to the RetroArch source during `sources_retroarch()`:
  - `record/drivers/record_ffmpeg.c`: adds `#ifndef AV_INPUT_BUFFER_MIN_SIZE` fallback (`16384`) and replaces `avcodec_close() + av_free()` with `avcodec_free_context()`
  - `cores/libretro-ffmpeg/ffmpeg_core.c`: replaces all `avcodec_close()` calls with `avcodec_free_context()`
- **`scriptmodules/emulators/retroarch.sh`**: calls `applyPatch` in `sources_retroarch()` to apply the above patch

All changes are guarded by `LIBAVCODEC_VERSION_INT >= AV_VERSION_INT(61, 3, 100)` so older FFmpeg versions (Raspberry Pi OS, Debian Bullseye/Bookworm, etc.) are **not affected**.

## Test plan

- [x] Built successfully on Ubuntu 26.04 with libavcodec 62.11.100 (`make -j$(nproc)` completes without errors)
- [ ] Verify no regression on Raspberry Pi OS (Debian Bookworm, FFmpeg 5.x/6.x)
- [ ] Verify `applyPatch` skip logic works correctly on re-runs (`.applied` marker file)

## Environment tested

| Field | Value |
|-------|-------|
| OS | Ubuntu 26.04 LTS (released 2026-04-23) |
| libavcodec | 62.11.100 |
| RetroArch | retropie-v1.19.0 |
| GCC | system default |

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

**Comment by cmitu** [comment]
This should be sent upstream - if upstream is not already aware of the build issue.

**Comment by manzolo** [comment]
Thanks for the review @cmitu!

The fix is actually already present in upstream  — it was merged as commit [](https://github.com/libretro/RetroArch/commit/21776a2e4f97e1e0cb88c30ef3a94e6a8e87aec3) on 2025-09-11 ("Attempt to fix ffmpeg 8.0 build errors"), using the same `FFMPEG8 = (LIBAVCODEC_VERSION_MAJOR >= 62)` guard.

The issue is that RetroPie-Setup currently pins `retropie/RetroArch` at tag **`retropie-v1.19.0`**, which predates that fix.

So the options are:

1. **Bump the tag** — update `rp_module_repo` in `retroarch.sh` to a newer `retropie-v` tag that has synced the upstream fix. This would be the cleanest long-term solution.
2. **Keep this patch** — apply it via `applyPatch` in `sources_retroarch()` as a stopgap until the tag is updated.

Happy to close this PR if the preferred path is to update the tag instead. Just let me know which direction you'd like to go.

**Comment by cmitu** [comment]
@manzolo If the upstream patch applies cleanly to our repository - on the 1.19 tag - then we may apply it there instead of doing it here. RetroPie specific patches are kept in the retropie/retroarch repository, instead of using local patches (in RetroPie-Setup).

While for bumping the RetroArch version there's a PR here, I think patching the 1.19 branch we have in our repo is better, if the FFmpeg changes can be cherry-picked easily (and rebasing over future RetroArch version is easier). Let's keep this PR opened while I try to do that.

**Comment by cmitu** [comment]
Created https://github.com/RetroPie/RetroArch/pull/11 which backports the upstream patches and should be merged with our 1.19 tree.

**Comment by cmitu** [comment]
Ok, so this should be fixed by the merging of https://github.com/RetroPie/RetroArch/pull/11, @manzolo can you check now ?

**Comment by manzolo** [comment]
@cmitu confirmed — RetroArch builds cleanly on Ubuntu 26.04 (FFmpeg 8.0.1, `LIBAVCODEC_VERSION_MAJOR = 62`) after the merge of RetroPie/RetroArch#11. Closing this PR as superseded.
