### ISSUE TITLE
Retropie Setup does not work in Ubuntu 26.04

### ISSUE THREAD

**Issue by Scoob1978** [RetroPie/RetroPie-Setup#4194]
### Description

I ran the retropie setup after upgrading from 24.10. It was a clean install. The set up script stops here. Hopefully there is an easy fix. 

record/drivers/record_ffmpeg.c:375:25: error: ‘AV_INPUT_BUFFER_MIN_SIZE’ undeclared (first use in this function); did you mean ‘AV_INPUT_BUFFER_PADDING_SIZE’?
  375 |    audio->outbuf_size = AV_INPUT_BUFFER_MIN_SIZE;
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~
      |                         AV_INPUT_BUFFER_PADDING_SIZE
record/drivers/record_ffmpeg.c:375:25: note: each undeclared identifier is reported only once for each function it appears in
CC gfx/video_crt_switch.c
record/drivers/record_ffmpeg.c: In function ‘ffmpeg_free’:
record/drivers/record_ffmpeg.c:952:7: error: implicit declaration of function ‘avcodec_close’; did you mean ‘avio_close’? [-Wimplicit-function-declaration]
  952 |       avcodec_close(handle->audio.codec);
      |       ^~~~~~~~~~~~~
      |       avio_close
make: *** [Makefile:209: obj-unix/release/record/drivers/record_ffmpeg.o] Error 1
make: *** Waiting for unfinished jobs....
cores/libretro-ffmpeg/ffmpeg_core.c: In function ‘libretro_ffmpeg_retro_unload_game’:
cores/libretro-ffmpeg/ffmpeg_core.c:2092:10: error: implicit declaration of function ‘avcodec_close’; did you mean ‘avcodec_license’? [-Wimplicit-function-declaration]
 2092 |          avcodec_close(sctx[i]);
      |          ^~~~~~~~~~~~~
      |          avcodec_license
make: *** [Makefile:207: obj-unix/release/cores/libretro-ffmpeg/ffmpeg_core.o] Error 1
Could not successfully build retroarch - RetroArch - frontend to the libretro emulator cores - required by all lr-* emulators (/home/bo/RetroPie-Setup/tmp/build/retroarch/retroarch not found).
/home/bo/RetroPie-Setup
Errors:
Could not successfully build retroarch - RetroArch - frontend to the libretro emulator cores - required by all lr-* emulators (/home/bo/RetroPie-Setup/tmp/build/retroarch/retroarch not found).

**Comment by cmitu** [comment]
@Scoob1978 it's been already reported, should be fixed when https://github.com/RetroPie/RetroArch/pull/11 is merged, closing also #4190.

**Comment by cmitu** [comment]
@Scoob1978 ok, can you try now ? The RetroArch fix has been merged. You need to clean the sources then re-install (from source) RetroArch.

**Comment by Scoob1978** [comment]
Retroarch compiled but emulation station does not 



= = = = = = = = = = = = = = = = = = = = =
Building 'emulationstation' : EmulationStation - Frontend used by RetroPie for launching emulators
= = = = = = = = = = = = = = = = = = = = =

Removing additional swap
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 has been removed from CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.

  Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.


-- Configuring incomplete, errors occurred!
make: *** No rule to make target 'clean'.  Stop.
make: *** No targets specified and no makefile found.  Stop.
Removing additional swap
Could not successfully build emulationstation - EmulationStation - Frontend used by RetroPie for launching emulators (/home/bo/RetroPie-Setup/tmp/build/emulationstation/emulationstation not found).
/home/bo/RetroPie-Setup

**Comment by cmitu** [comment]
`emulationstation-dev` should work (from the _experimental_ packages section).

**Comment by Scoob1978** [comment]
That worked. Thank you so much.

**Comment by cmitu** [comment]
@Scoob1978 ok, thanks for the report. We'll backport the CMake related commits to the `stable` branch of EmulationStation, just to start support for 26.94, but I expect you'll see similar issues with upstream projects.
I'll leave this open until EmulationStation is updated.

**Comment by cmitu** [comment]
This should be fixed now, after the `stable` branch of RetroPie/EmulationStation has been updated with `cmake` 4.0 support in https://github.com/RetroPie/EmulationStation/pull/912
